typography_spectrum: 0.8551843736786395
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7919165103230625
  lightness: 0.9175645674113184
  saturation: 0.7355238606687635
  rhythmicContrast: 0.4019982600584626
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3913296367973089
analytics:
  google: UA-74427303-1
  facebook: null
  twitter: null
name: Rob Test
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
